### ISSUE TITLE
UnboundLocalError: local variable 'ver' referenced before assignment

### ISSUE THREAD

**Issue by zhanjiahui** [Twizwei/VideoEditGAN#1]
Sorry to bother.
I spilt a video to frames using this scripts:
`python scripts/vid2frame.py --pathIn /mnt/lab/zjh/PROJECT/STIT/datasets/hat_hand.mp4 --pathOut out/hat_hand/frames`
And then single_video_smooth.py was pasted to 3DDFA_V2 folder.
Then I ran these scripts:
`cd 3DDFA_V2`
`python single_video_smooth.py -f out/hat_hand/frames`
​Unfortunately, an error occurred:
```
(videogan) zjh@byleth:~/PROJECT/VideoEditGAN/3DDFA_V2$ python single_video_smooth.py -f out/hat_hand/frames
Traceback (most recent call last):
  File "single_video_smooth.py", line 170, in <module>
    main(args)
  File "single_video_smooth.py", line 131, in main
    queue_ver.append(ver.copy())
UnboundLocalError: local variable 'ver' referenced before assignment
```
Is there any way to solve this problem? Thank you again for your wonderful work.

**Comment by youngalong** [comment]
@zhanjiahui I have resolved this issue. Perhaps you should check if the input video path is correct.

**Comment by zhanjiahui** [comment]
> @zhanjiahui I have resolved this issue. Perhaps you should check if the input video path is correct.

@youngalong Thank you for your reply. 
(Although it's been so long since this issue, I've almost forgotten about it :)🤣
